name: Artefact Builder
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout 
      uses: actions/checkout@v2 
    - name: set reponame
      run: echo "::set-env name=REPONAME::$(basename `pwd`)"
    - name: set artversion
      run: echo "::set-env name=ARTVERSION::$(grep '"version"' ./src/manifest.json  | cut -d'"' -f4)"
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.REPONAME }}-${{ env.ARTVERSION }}.xpi
        path: ./src/
