name: Artefact Builder
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout 
      uses: actions/checkout@v2 
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        path: ./src/
